### ISSUE TITLE
print.environment interferes with dplyr

### ISSUE THREAD

**Issue by akonecny** [mjdufort/RNAseQC#2]
Hello, I've been using RNAseQC in a project. I was experiencing problems very similar to this thread [https://github.com/rstudio/rstudio/issues/6645], where my rsession would randomly hang long after running a section of code. I pinned it down to to the RNAseQC not playing nice with the {dplyr} namespace.

Thought you would appreciate knowing and wanted to inquire if you had any work arounds? 

# To recreate problem
library(RNAseQC)
dplyr <- asNamespace("dplyr")
print(dplyr)

**Comment by mjdufort** [comment]
Thank you for tracing this problem.  I was able to reproduce the error, and traced it to a dependency on an Rfast function within `estimate_saturation`.  Once I refactored the code to remove this dependency, the error no longer occurred.

The updated package version should resolve this problem.  However, estimate_saturation is now much slower, as I could not find a comparable alternative to the Rfast function colTabulate.  If in the future Rfast resolves their `print.environment` issue, I will revert to using that functionality.
